### ISSUE TITLE
Achievements, Nano Disappeared

### ISSUE THREAD

**Issue by CatTriesGithub** [running-coder/NanoBrowserQuest#3]
As the title says, I log in and check my achievements and they are all gone. The nano earned from the achievements is gone too. Gems and nano potions are still there. 

I tried the Boss, died, and my game froze and then this started happening right after.

**Comment by tombertrand** [comment]
I had that once but was unable to repro, do you get it constantly for your character only?

**Comment by tombertrand** [comment]
Should be resolved now, lmk if it keeps happening

**Comment by CatTriesGithub** [comment]
Hey sorry, I feel asleep.

Yeah it happens almost every time I log in.

Just checked, looks like it’s all back.

Thanks!

Cat
________________________________

**Comment by andrewclark3244** [comment]
2021...
What a time before...
