### ISSUE TITLE
Weapons went missing after upgrade.

### ISSUE THREAD

**Issue by MrUSBEN** [running-coder/NanoBrowserQuest#4]
When i was upgrading magic sword on anvil and didn't preview it and just clicked upgrade. It vanished.
I tried it again with axe without preview and it also vanished. I am down 2 OP weapons. That sucks. 

Please fix this, if the weapon upgrade preview is not clicked the weapon should either return to inventory or auto upgrade and show in the preview slot.

**Comment by tombertrand** [comment]
You saw that the higher the level of an item the higher are the chances of destroying it during an upgrade? You will see the % per level above the upgrade / preview bottons after dropping an item in the left slot. Or did something else happened? Can you record a video / gif and upload it here?
![134805C9-82E9-4DD0-8323-57551788896F](https://user-images.githubusercontent.com/19352322/140747311-72b91928-1dca-4c41-b0f8-64f91370bdc9.png)

**Comment by MrUSBEN** [comment]
Well its my bad then, i didn't know that the items could be destroyed if upgrade failed. 
It makes sense now, a good way to have value for duplicate dropped items. 
Now that it is clear, i must say i love your game. Simple yet soo fun to play. 
Thankyou for making the game and your time. 

Sent from Yahoo Mail on Android 
 
  On Mon, 8 Nov 2021 at 6:38 pm, Tom ***@***.***> wrote:   


You saw that the higher the level of an item the higher are the chances of destroying it during an upgrade? You will see the % per level above the upgrade / preview bottons after dropping an item in the left slot. Or did something else happened? Can you record a video / gif and upload it here?


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tombertrand** [comment]
Awesome, glad to hear! The upgrade panel is currently missing a success / fail animation to make it more obvious (it's currently only displayed on the Anvil as yellow/success or red/fail). Will keep that in mind!
