### ISSUE TITLE
Open Source?

### ISSUE THREAD

**Issue by thekesslereffect** [running-coder/NanoBrowserQuest#5]
Hi! Are you able to make this open source? I would really love to fork this for the banano community. Thanks!

**Comment by tombertrand** [comment]
Thanks for playing NBQ, the code will unfortunately not go opensource for various reasons, one of them is because it holds a payment / faucet system

**Comment by Veradictus** [comment]
That's a direct violation of the MPL2.0 license, unless you have completely rewritten the code, which, from analyzing your website, you have not. Aside from uglifying the JS code to the point it's just hexadecimals, there are still many noticeable similarities to the BQ codebase.

**Comment by Veradictus** [comment]
<img width="869" alt="Screenshot 2023-09-20 at 1 53 06 PM" src="https://github.com/running-coder/NanoBrowserQuest/assets/45127244/b56a459d-4f4f-4c6d-b5da-ef80cd00d3e9">
This isn't something you just choose not to do.

**Comment by octoshrimpy** [comment]
it looks like it's also a violation of the assets CC-BY-SA 3.0:
https://creativecommons.org/licenses/by-sa/3.0/
![image](https://github.com/running-coder/NanoBrowserQuest/assets/7097172/4e5f8160-d5fe-4422-81e2-072483570f38)

**Comment by Mouradif** [comment]
@tombertrand That's a lame excuse, just put private keys in git-ignored env files

**Comment by tombertrand** [comment]
> @tombertrand That's a lame excuse, just put private keys in git-ignored env files

that just shows me how ignorant you can be when it come to coding, I'm not here to argue, gl in your endavour

**Comment by Mouradif** [comment]
@tombertrand I've written faucets for a private network and there are many that are open source. If you have sensitive data in your faucet code, you're doing it wrong. Regardless, you are violating the MPL license.
